# Generated by Django 2.2.7 on 2019-11-11 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_app', '0002_socialnetworks_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetworks',
            name='type_cn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD_app.socialNetworks_types'),
        ),
    ]
